imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

sonata_cache:
    caches:
        apc:
            token:  apc_test     # token used to clear the related cache
            prefix: mw_test      # prefix to ensure there is no clash between instances
            servers:
                - { domain: mw.local, ip: 127.0.0.2, port: 80}

sk_media_api:
  media_provider_api:
    debug_mode: true
    providers: 
      amazon_provider:
        access_params:
          amazon_public_key: apuk
          amazon_private_key: aprk
          amazon_associate_tag: aat
        amazon_signed_request:
          class: Sk\MediaApiBundle\Tests\MediaProviderApi\TestAmazonSignedRequest
      youtube_provider:
        google_service_youtube: 
          class: Sk\MediaApiBundle\Tests\MediaProviderApi\TestGoogleServiceYouTube 