#sk_front_end:
#    resource: "@SkFrontEndBundle/Controller/"
#    type:     annotation
#    prefix:   /

sk_media_api_bundle:
    type: rest
    resource: "@SkMediaApiBundle/Resources/config/routing.yml"
    prefix:   /api

fos_comment_bundle:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /fosapi

sk_comment:
    resource: "@SkCommentBundle/Controller/"
    type:     annotation
    prefix:   /
    


